
discordwebhook:

title: "ルールブック"
author: "Nixxz_"
pages:
  - "1.サバイバルサーバーでのルール"
  - "このサーバーでのルール\n\n\
    人のものを勝手に取らない\n\n\
    人の嫌がることをしない\n\n\
    人の建築内に勝手に侵入しない\n\n\
    最低限のマナーを守って生活しましょう。"
  - "他にも。。。\n\n\
    ・サーバーに負荷のかかる行動を控える（看板を設置しすぎない、MOBを増やしすぎない、複雑・高速なレッドストーン回路を控える）\n\n\
    ・ユーザー間の争いを防ぐために、他人の建築物を（よっぽどのことがない限り）無許可で壊さない\n\n\
    窃盗された場合はdiscordで言っていただければ、犯人を特定しますのでご安心を"
  - "QA\n\n\

     何をすればいいかわからない\n\n\
     ・このワールドはサバイバルとなっているので、マナーを守って自由にさばいばるしてください。\n\n\

     家はどこに建てればいいの？\n\n\
     ・空いている土地（場合によってはトラブルになるかもしれないので不安であれば聞いてください）"
  - "2.クリエイティブサーバーでのルール"