lobby: false

rulebook:
  title: ルールブック
  author: jishaku0521
  pages:
    - |-
      1.はじめに
       ようこそはね鯖へ！
      このサーバーに参加しているみんなは、自由に楽しく生活しています。  みんなが楽しくマイクラをするには、みんながルールを守らなくてはいけません。
      そんなルールが書いてあるのがこの本です。
      しっかり読んでから参加してくださいね！
    - |-
      2.確認事項

      ・13歳以上である
      ・ハッククライアント、forge、fabric、5zip等を使用して入ってない
      （optifineは可）
      ・Discordのルールなどをしっかり読んだ

      これらの条件に当てはまらないと参加できません。
    - |-
      3.このサーバーでのルール

      人のものを勝手に取らない

      人の嫌がることをしない

      人の建築内に勝手に侵入しない

      最低限のマナーを守って生活しましょう。
    - |
      他にも。。。
      ・サーバーに負荷のかかる行動を控える（看板や額縁を設置しすぎない、MOBを増やしすぎない、複雑・高速なレッドストーン回路を控える）

      ・参加者間の争いを防ぐために、他人の建築物を（よっぽどのことがない限り）無許可で壊さない
    - |-
      窃盗された、勝手に壊されたなどの被害がありましたら、discordの
      ＃建築物の破損＆アイテムの盗難-被害報告所
      へ、報告して頂ければ対応します。
    - |2-

      4.初回参加時の行動

      サバイバルサーバーに参加すると、「新規の方はこちらへ」などと看板が立っているので、「新規です」とチャットで発言をしてからその看板に従い進んでください。
      その後は注意事項や各施設の案内を
      Terumitto_129
      という人がしてくれます。
    - |+
      5.その他注意事項

      ・溶岩、火打石を使用することは可能ですが、チャットに警告文が出ます

      ・名前の付いたMOBも殺すと同様にチャットに出ます

      ・TNTは１発アウトなので間違えておかないようにしましょう

    - |-
      ・ビーコンは重たくなるので使わないでください（代わりのものを貿易できます）

      ・ファントムはいません（貿易で買うことができます）

      ・整地されている土地はたいてい誰かのものです。自分で整地するか、許可を得て使いましょう。

      ・トラップタワーの追加は禁止です
    - |
      ・氷渡りのエンチャント、不法侵入、過度な絵画は禁止

      ・MOBの大量繁殖は禁止（牧場では１０体程度に）

      ・チャットの発言には節度を持って仲良く

      ・もめごとには注意をし、身勝手な行動はしない
    - "・公共の施設や村人、ベットを壊さない・殺さない\n\n\n・荒らし、窃盗は\n      \n           BAN\n  \n  です"
    - |-
      何か疑問・質問があれば気軽に相談してください！



            ルールを守って

         楽しいはね鯖生活を！