name: HaneServerLobby
version: ${project.version}
main: net.serveron.hane.haneserverlobby.HaneServerLobby
api-version: 1.16
commands:
  rulebook:
    usage: /rulebook
    description: hane server asist plugin

permissions:
  rulebook.*:
    description: Gives access to all commands
    default: op